/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaplayground;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//        Table roundTable = new Table();
//        roundTable.setShape("round");
//
//        System.out.println(roundTable);
        Marker marker = new Marker(true, 2);
        marker.unCap();
        marker.write("Hello");
        System.out.println(marker);
        Marker marker2 = new Marker(true, 2);
        System.out.println(marker2);
        System.out.println(marker2.getInkLevel());
        System.out.println(marker2 instanceof Marker);
    }
}
